### ISSUE TITLE
Setting base color

### ISSUE THREAD

**Issue by simonbengtsson** [Autodesk/ADNetPromoterScoreSurvey-iOS#5]
Currently you have to set each and every color to change to your app's base color. Would you accept a PR adding this method to reduce the boilerplate needed for simpler customizations?

In `NPSAppearance`:

    func setBaseColor(_ color: UIColor) {
        let scoreLook = scoreQuestionViewAppearance
        scoreLook.sliderThumbColor = adjustBrightness(for: color, by: -10)
        scoreLook.sliderMinimumTrackTicksColor = UIColor.black.withAlphaComponent(0.2)
        scoreLook.highRankTitleMarkedColor = color
        scoreLook.lowRankTitleMarkedColor = color
        scoreLook.sliderMinimumTrackBackgroundColor = color
        scoreLook.selectedScoreTextColor = color
        scoreLook.sendButtonBackgroundColor = color
        
        let feedbackLook = feedbackQuestionViewAppearance
        feedbackLook.sendButtonBackgroundColor = color
        feedbackLook.editScoreButtonTextColor = color
        
        thankYouViewAppearance.bottomBannerColor = color
    }
    
    private func adjustBrightness(for color: UIColor, by percentage: CGFloat) -> UIColor? {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
        color.getRed(&r, green: &g, blue: &b, alpha: &a)
        return UIColor(red: min(r + percentage / 100, 1.0),
                       green: min(g + percentage / 100, 1.0),
                       blue: min(b + percentage / 100, 1.0),
                       alpha: a)
    }

**Comment by Applitom** [comment]
Hi @simonbengtsson,
Thank you for this suggestion, It's a cool idea!
I would love to merge a PR with this implementation :-)

**Comment by Applitom** [comment]
Thank you very much for this contribution, the PR was merged to master and this feature will be part of the next release
